### ISSUE TITLE
Failed to convert type

### ISSUE THREAD

**Issue by aksonov** [mobxjs/mst-gql#21]
Got following output:
```
Detected types: 
  - [OBJECT] RootQueryType
  - [SCALAR] UUID
  - [OBJECT] Bot
  - [SCALAR] String
  - [SCALAR] DateTime
  - [SCALAR] Int
  - [OBJECT] BotItemsConnection
  - [OBJECT] BotItemsEdge
  - [OBJECT] BotItem
  - [OBJECT] Media
  - [INTERFACE] User
  - [ENUM] UserBotRelationship
  - [OBJECT] BotsConnection
  - [OBJECT] BotsEdge
  - [OBJECT] PageInfo
  - [SCALAR] Boolean
  - [ENUM] UserContactRelationship
  - [OBJECT] ContactsConnection
  - [OBJECT] ContactsEdge
  - [OBJECT] Hidden
  - [OBJECT] Presence
  - [ENUM] PresenceStatus
  - [SCALAR] Float
  - [ENUM] SubscriptionType
  - [OBJECT] SubscribersConnection
  - [OBJECT] SubscribersEdge
  - [OBJECT] CurrentUser
  - [OBJECT] BlocksConnection
  - [OBJECT] BlocksEdge
  - [OBJECT] Block
  - [OBJECT] BlockedUser
  - [OBJECT] ConversationsConnection
  - [OBJECT] ConversationsEdge
  - [OBJECT] Message
  - [ENUM] MessageDirection
  - [OBJECT] FriendsConnection
  - [OBJECT] FriendsEdge
  - [OBJECT] Contact
  - [OBJECT] LocationEventsConnection
  - [OBJECT] LocationEventsEdge
  - [OBJECT] LocationEvent
  - [ENUM] LocationEventType
  - [OBJECT] Location
  - [OBJECT] UserLocationLiveSharesConnection
  - [OBJECT] UserLocationLiveSharesEdge
  - [OBJECT] UserLocationLiveShare
  - [OBJECT] OtherUser
  - [OBJECT] LocationsConnection
  - [OBJECT] LocationsEdge
  - [OBJECT] MessagesConnection
  - [OBJECT] MessagesEdge
  - [OBJECT] InvitationsConnection
  - [OBJECT] InvitationsEdge
  - [OBJECT] Invitation
  - [INPUT_OBJECT] Point
  - [OBJECT] LocalBots
  - [OBJECT] LocalBotsCluster
  - [OBJECT] BotCluster
  - [SCALAR] AInt
  - [ENUM] NotificationType
  - [OBJECT] NotificationsConnection
  - [OBJECT] NotificationsEdge
  - [OBJECT] Notification
  - [UNION] NotificationData
  - [OBJECT] BotInvitationNotification
  - [OBJECT] BotInvitation
  - [OBJECT] BotInvitationResponseNotification
  - [OBJECT] BotItemNotification
  - [OBJECT] GeofenceEventNotification
  - [ENUM] GeofenceEvent
  - [OBJECT] LocationShareEndNotification
  - [OBJECT] LocationShareNotification
  - [OBJECT] UserInvitationNotification
  - [OBJECT] UserBulkLookupResult
  - [OBJECT] RootMutationType
  - [INPUT_OBJECT] FriendNameInput
  - [OBJECT] FriendNamePayload
  - [OBJECT] ValidationMessage
  - [OBJECT] ValidationOption
  - [OBJECT] UserLocationCancelSharePayload
  - [INPUT_OBJECT] PresenceStatusInput
  - [OBJECT] PresenceStatusPayload
  - [INPUT_OBJECT] UserUnblockInput
  - [OBJECT] UserUnblockPayload
  - [INPUT_OBJECT] UserUpdateInput
  - [INPUT_OBJECT] UserParams
  - [OBJECT] UserUpdatePayload
  - [INPUT_OBJECT] BotDeleteInput
  - [OBJECT] BotDeletePayload
  - [INPUT_OBJECT] BotCreateInput
  - [INPUT_OBJECT] UserLocationUpdateInput
  - [INPUT_OBJECT] BotParams
  - [OBJECT] BotCreatePayload
  - [INPUT_OBJECT] SendMessageInput
  - [OBJECT] SendMessagePayload
  - [INPUT_OBJECT] UserLocationLiveShareInput
  - [OBJECT] UserLocationLiveSharePayload
  - [INPUT_OBJECT] UserBlockInput
  - [OBJECT] UserBlockPayload
  - [INPUT_OBJECT] UserInviteRedeemCodeInput
  - [OBJECT] UserInviteRedeemCodePayload
  - [INPUT_OBJECT] FactoryInsertInput
  - [INPUT_OBJECT] AtomParam
  - [INPUT_OBJECT] BoolParam
  - [INPUT_OBJECT] FloatParam
  - [INPUT_OBJECT] IntParam
  - [INPUT_OBJECT] StringParam
  - [OBJECT] FactoryInsertPayload
  - [INPUT_OBJECT] UserHideInput
  - [OBJECT] UserHidePayload
  - [INPUT_OBJECT] FriendBulkInviteInput
  - [OBJECT] FriendBulkInvitePayload
  - [OBJECT] FriendBulkInviteResult
  - [ENUM] BulkInviteResult
  - [INPUT_OBJECT] MediaUploadParams
  - [OBJECT] MediaUploadPayload
  - [OBJECT] MediaUploadResult
  - [OBJECT] RequestHeader
  - [INPUT_OBJECT] AuthenticateInput
  - [OBJECT] AuthenticatePayload
  - [INPUT_OBJECT] PushNotificationsDisableInput
  - [OBJECT] PushNotificationsDisablePayload
  - [INPUT_OBJECT] BotUpdateInput
  - [OBJECT] BotUpdatePayload
  - [INPUT_OBJECT] UserLocationCancelShareInput
  - [INPUT_OBJECT] MediaDeleteParams
  - [OBJECT] MediaDeletePayload
  - [OBJECT] UserDeletePayload
  - [INPUT_OBJECT] BotInvitationRespondInput
  - [OBJECT] BotInvitationRespondPayload
  - [INPUT_OBJECT] BotUnsubscribeInput
  - [OBJECT] BotUnsubscribePayload
  - [OBJECT] UserInviteMakeCodePayload
  - [INPUT_OBJECT] BotInviteInput
  - [OBJECT] BotInvitePayload
  - [OBJECT] UserLocationGetTokenPayload
  - [INPUT_OBJECT] NotificationDeleteInput
  - [OBJECT] NotificationDeletePayload
  - [INPUT_OBJECT] BotItemDeleteInput
  - [OBJECT] BotItemDeletePayload
  - [INPUT_OBJECT] FollowInput
  - [OBJECT] FollowPayload
  - [INPUT_OBJECT] BotItemPublishInput
  - [OBJECT] BotItemPublishPayload
  - [INPUT_OBJECT] FriendDeleteInput
  - [OBJECT] FriendDeletePayload
  - [INPUT_OBJECT] BotSubscribeInput
  - [OBJECT] BotSubscribePayload
  - [OBJECT] UserLocationUpdatePayload
  - [INPUT_OBJECT] PushNotificationsEnableInput
  - [ENUM] NotificationPlatform
  - [OBJECT] PushNotificationsEnablePayload
  - [INPUT_OBJECT] FriendInviteInput
  - [OBJECT] FriendInvitePayload
  - [OBJECT] RootSubscriptionType
  - [OBJECT] VisitorUpdate
  - [ENUM] VisitorAction
  - [UNION] NotificationUpdate
  - [OBJECT] NotificationDeleted
  - [OBJECT] UserLocationUpdate
  - [OBJECT] __Schema
  - [OBJECT] __Type
  - [ENUM] __TypeKind
  - [OBJECT] __Field
  - [OBJECT] __InputValue
  - [OBJECT] __EnumValue
  - [OBJECT] __Directive
  - [ENUM] __DirectiveLocation
  - [SCALAR] ID
Warning: no root types are configured. Probably --roots should be set. Auto-detected and using the following types as root types: 
/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:275
          throw new Error(
          ^

Error: Failed to convert type {"kind":"INTERFACE","name":"User","ofType":null}. PR Welcome!
    at handleFieldType (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:275:17)
    at handleField (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:239:34)
    at type.fields.filter.map.field (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:184:21)
    at Array.map (<anonymous>)
    at handleObjectType (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:184:8)
    at types.filter.forEach.type (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:88:22)
    at Array.forEach (<anonymous>)
    at generateTypes (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:81:8)
    at generate (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/generate.js:42:3)
    at main (/Users/aksonov/Documents/Test/node_modules/mst-gql/generator/mst-gql-scaffold.js:96:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by mweststrate** [comment]
Looks like referring to an interface from an object field type is not supported by the generator at the moment. Currently interfaces are merged into the models that implement them. 

Instead, probably separate models should be generated and implementations should extend them. 

Or alternatively: the interface could be defined as the union of all concrete object types that implement them.

**Comment by aksonov** [comment]
Thanks for quick response! Any quick workaround to generate stubs?

**Comment by mweststrate** [comment]
You could adjust the generator to skip fields that have an interface type

Op vr 31 mei 2019 22:06 schreef Pavel Aksonov <notifications@github.com>:

**Comment by onomated** [comment]
Just ran into this myself with my `USER` interface.  @aksonov worked on any changes to the generator yet?

**Comment by dpnolte** [comment]
@onomated @aksonov  I made a start in #23 to support interface fields. Maybe you can check if it works for you?

**Comment by onomated** [comment]
@dpnolte Works great! Thanks for introducing inline fragments to the QueryBuilder as well.  
@mweststrate perfect timing on this component as well.  Was just migrating from ApolloClient to mobx/libx and I stumbled on this
Cheers!

**Comment by dpnolte** [comment]
Thanks, then i'll close this issue. #23 will be part of the next release
