### ISSUE TITLE
Error: Unknown type "AWSJSON"

### ISSUE THREAD

**Issue by hazemturki** [mobxjs/mst-gql#309]
Not sure what is proper way of write issues, but I am running into this error when I try to generate proper mutations.
Tried to temporarily change "AWSJSON" to string just to generate the mutation in the model, but the server refused, although AWSJSON is just a string (has to be valid json).

```yarn mst-gql --format ts --outDir src/lib/models schema.graphql yarn run v1.9.4
$ ****/node_modules/.bin/mst-gql --format ts --outDir src/lib/models schema.graphql
mst-gql-scaffold.js --format=ts --outDir=****/src/lib/models schema.graphql
****/node_modules/mst-gql/node_modules/graphql/validation/validate.js:108
    throw new Error(errors.map(function (error) {
    ^

Error: Unknown type "AWSJSON".
    at assertValidSDL (****/node_modules/mst-gql/node_modules/graphql/validation/validate.js:108:11)
    at buildASTSchema (****/node_modules/mst-gql/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchema (****/node_modules/mst-gql/node_modules/graphql/utilities/buildASTSchema.js:462:10)
    at main (****//node_modules/mst-gql/generator/mst-gql-scaffold.js:83:28)
    at Object.<anonymous> (****/node_modules/mst-gql/generator/mst-gql-scaffold.js:117:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What is a good way to handle such occurrences.
Thanks a lot

**Comment by beepsoft** [comment]
@hazemturki can you maybe share your schema.graphql? Is AWSJSON a scalar type? mst-gql should handle it and generate `any` type in typescript.

**Comment by hazemturki** [comment]
@beepsoft Adding AWSJSON as a scalar type worked.
Thanks a lot!
